apiVersion: v1
kind: Service
metadata:
  name: deck
  namespace: kubeedge-prowbot
spec:
  ports:
  - name: main
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: deck
  type: NodePort
