apiVersion: v1
kind: Service
metadata:
  labels:
    app: tide
  namespace: kubeedge-prowbot
  name: tide
spec:
  selector:
    app: tide
  ports:
  - name: main
    nodePort: 31351
    port: 80
    targetPort: 8888
  type: NodePort
